### ISSUE TITLE
`docker build` fails with SetuptoolsOutdatedWarning: your setuptools is too old (feature/commons)

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/cgp-dashboard-service#70]
```
$ git clone https://github.com/DataBiosphere/cgp-dashboard-service.git
$ cd cgp-dashboard-service/
$ git fetch
$ git checkout feature/commons
$ docker build .
....
Step 10/36 : RUN pip install -r /app/requirements.txt
 ---> Running in 8624cfc6e106
/usr/local/lib/python2.7/dist-packages/cffi/model.py:531: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Collecting alembic==0.8.10 (from -r /app/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f0/7d/7fcda63887d9726e0145e98802baf374ec8cf889325e469194cd7926c98e/alembic-0.8.10.tar.gz (976kB)
Collecting appdirs==1.4.0 (from -r /app/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/7b/8b/eebc6e2002a1e0383f1c7108d0111d4d33ea93bf417d7e19e43ec9b87b2b/appdirs-1.4.0-py2.py3-none-any.whl
Collecting APScheduler==3.3.1 (from -r /app/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/22/ff/eb9d27536f25253c09573cc7afc6db9708ea0abad02f5ac031b412d5cbda/APScheduler-3.3.1-py2.py3-none-any.whl (56kB)
Collecting backports-abc==0.5 (from -r /app/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7d/56/6f3ac1b816d0cd8994e83d0c4e55bc64567532f7dc543378bd87f81cebc7/backports_abc-0.5-py2.py3-none-any.whl
Collecting bagit==1.6.3 (from -r /app/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/a8/92/da887c1cf04d3c5a0f4ef87a7608eae88f1f418cf650f1811ccb142687b9/bagit-1.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6EHcjK/bagit/setup.py", line 75, in <module>
        'Programming Language :: Python :: 3.6',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 10, in version_keyword
      File "build/bdist.linux-x86_64/egg/setuptools_scm/version.py", line 44, in _warn_if_setuptools_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6EHcjK/bagit/
The command '/bin/sh -c pip install -r /app/requirements.txt' returned a non-zero code: 1
```

```
natan ~> docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:38 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:45 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by natanlao** [comment]
Closed by #72
